[colors]
background = #1E1E2E
background-alt = #1E1E2E
foreground = #C5C8C6
primary = #C5C8C6
secondary = #C5C8C6
alert = #A54242
disabled = #707880

[bar/main]
width = 100%
height = 24pt
radius = 0
background = ${colors.background}
foreground = ${colors.foreground}

; Add a bit of transparency
dim-value = 1.0

line-size = 3pt
border-size = 0pt

padding-left = 0
padding-right = 1

module-margin = 1

separator = " "
separator-foreground = ${colors.disabled}

font-0 = "ComicShannsMono Nerd Font:style=Regular:size=12;2"
font-1 = "ComicShannsMono Nerd Font Mono:style=Regular:size=12"
font-2 = "JetBrainsMono Nerd Font:style=Regular:size=12"

modules-left = xworkspaces
modules-center = date
modules-right = coffee pulseaudio wlan battery power-menu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/coffee]
type = custom/script
exec = ~/.config/polybar/coffee.sh
interval = 1
label = %output%
label-font = 1

[module/pulseaudio]
type = internal/pulseaudio
sink = @DEFAULT_SINK@

format-volume = ""
format-muted = ""

[module/wlan]
type = internal/network
interface = wlp4s0
interval = 3.0

format-connected = %{A1:~/.config/rofi/wifi-menu-new.sh &:}󰤨%{A}
format-disconnected = %{A1:~/.config/rofi/wifi-menu-new.sh &:}󰤮%{A}

label-connected = 
label-connected-foreground = ${colors.foreground}
label-disconnected = 
label-disconnected-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1
date = %a %b %d %I:%M %p
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.foreground}

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 98
format-charging = ""
format-discharging = ""
label-charging = %format%
label-discharging = %format%
label-full = ""

[module/power-menu]
type = custom/text
format = ⏻
format-padding = 1
format-margin-left = -3

click-left = ~/.config/polybar/power-menu.sh

[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/main]
override-redirect = false
